<<<<<<< HEAD
# Generated by Django 3.0.5 on 2020-05-04 18:11
=======
# Generated by Django 3.0.4 on 2020-05-04 18:05
>>>>>>> 56eb90a8ba32388c69fa5b7232013c0926513029

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('publisher', models.CharField(max_length=100)),
            ],
        ),
    ]
